[project]
name = "estudos-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wildson Romeu", email = "wildsonprojetos@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
estudos-python = "estudos_python:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
